contact/urls.py
from django.contrib import admin
from django.urls import path

from .views import emailView, successView

app_name = 'contact'

urlpatterns = [
    path('', emailView, name='email'),
    path('success/', successView, name='success')
]

myfoodrecipes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from recipes.sitemap import Static_Sitemap
from recipes.sitemap import Recipe_Sitemap

sitemaps = {
    'recipes': Recipe_Sitemap(),
    'static': Static_Sitemap(),
}

urlpatterns = [
    path('', include('recipes.urls')),
    path('contact/', include('contact.urls')),
    path('adm/', admin.site.urls),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="generator" content="">
    <title>All Food Recipes | {{ title }}</title>

    <link rel="canonical" href="">
    <!-- Google Web Font-->
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cabin" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Droid+Sans" rel="stylesheet">
    <!-- Bootstrap core CSS -->
    {% comment %} <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}"> {% endcomment %}
    <link rel="stylesheet" href="https://static.allfoodrecipes.net/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
     
    <style> 
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <!-- Font Awesome -->
   <link rel="stylesheet" href="{% static 'css/fontawesome/css/fontawesome.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/fontawesome/css/regular.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/fontawesome/css/solid.min.css'%}">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-156663963-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-156663963-1');
    </script>
    
    <meta name="p:domain_verify" content="331ffb9364d14514dc102c9ebf911838"/>
  </head>
<body>
<header>
  <nav class="navbar navbar-expand-md navbar-dark bg-purple fixed-top shadow">
    <div class="container d-flex justify-content-between">
      <a href="{% url 'index' %}" class="navbar-brand d-flex align-items-center">
        <strong>AllFoodRecipes</strong>
      </a>
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
          <div class="navbar-nav">
              <a href="{% url 'about' %}" class="nav-item nav-link">About</a>
              <a href="{% url 'tags' %}" class="nav-item nav-link">Tags</a>
              &nbsp;
              <form class="form-inline" method="GET" action="{% url 'search'  %}">
              <div class="input-group" id="search-bar">                 
                  <input type="text" name="q" class="form-control" placeholder="Search">
                  <div class="input-group-append">
                      <button type="submit" class="btn btn-secondary"><i class="fas fa-search"></i></button>
                  </div>
              </div>
          </form>
          </div>
          <div class="navbar-nav">
              <a href="{% url 'disclaimer' %}" class="nav-item nav-link">Disclaimer</a>
              <a href="{% url 'privacy' %}" class="nav-item nav-link">Privacy Policy</a>
              <a href="{% url 'terms' %}" class="nav-item nav-link">Term & Conditions</a>
              <a href="{% url 'contact:email' %}" class="nav-item nav-link">Contact</a>
          </div>
      </div>
    </div>
  </nav>
</header>

<main role="main">

  <section class="feature text-left">
    {% block features %}
    {% endblock features %}
  </section>

  <div class="main-content bg-light">
    <div class="container">

      <div class="row">
        {% block content %}
        {% endblock content %}
    </div>
  </div>

</main>

<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p>AllFoodRecipes is the place that can help you to get any references about <br>food recipes, you can search any food recipes by tags or search bar.  </p>
  </div>
</footer>
  <script src="{% static "js/jquery-3.4.1.min.js"%}" type="text/javascript"></script>
  <script src="{% static "js/jquery-3.4.1.min.js"%}" type="text/javascript"></script>
  <script src="{% static "js/bootstrap.bundle.min.js"%}" type="text/javascript"></script>
  <script src="{% static "js/script.js"%}" type="text/javascript"></script>
 <script src="{% static "js/lazy.js"%}" type="text/javascript"></script>
</body>
</html>

templates/single.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="generator" content="">
    <meta name="referrer" content="no-referrer" />
    <title>All Food Recipes | {{ title }}</title>

    <link rel="canonical" href="">
    <!-- Google Web Font-->
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cabin" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Droid+Sans" rel="stylesheet">
    <!-- Bootstrap core CSS -->
    {% comment %} <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}"> {% endcomment %}
    <link rel="stylesheet" href="https://static.allfoodrecipes.net/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
     
    <style> 
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'css/fontawesome/css/fontawesome.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/fontawesome/css/regular.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/fontawesome/css/solid.min.css'%}">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-156663963-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-156663963-1');
    </script>

    <script async defer data-pin-hover="true" data-pin-tall="true" src="//assets.pinterest.com/js/pinit.js"></script>
  </head>
<body>
<header>
  <nav class="navbar navbar-expand-md navbar-dark bg-purple fixed-top shadow">
    <div class="container d-flex justify-content-between">
      <a href="{% url 'index' %}" class="navbar-brand d-flex align-items-center">
        <strong>AllFoodRecipes</strong>
      </a>
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
          <div class="navbar-nav">
              <a href="{% url 'about' %}" class="nav-item nav-link">About</a>
              <a href="{% url 'tags' %}" class="nav-item nav-link">Tags</a>
              &nbsp;
              <form class="form-inline" method="GET" action="{% url 'search'  %}">
              <div class="input-group" id="search-bar">                 
                  <input type="text" name="q" class="form-control" placeholder="Search">
                  <div class="input-group-append">
                      <button type="submit" class="btn btn-secondary"><i class="fa fa-search"></i></button>
                  </div>
              </div>
          </form>
          </div>
          <div class="navbar-nav">
              <a href="{% url 'disclaimer' %}" class="nav-item nav-link">Disclaimer</a>
              <a href="{% url 'privacy' %}" class="nav-item nav-link">Privacy Policy</a>
              <a href="{% url 'terms' %}" class="nav-item nav-link">Term & Conditions</a>
              <a href="{% url 'contact:email' %}" class="nav-item nav-link">Contact</a>
          </div>
      </div>
    </div>
  </nav>
</header>

<main role="main">

  <section class="feature text-left">
    {% block features %}
    {% endblock features %}
  </section>

  <div class="main-content bg-light">
    <div class="container">

      <div class="row">
        {% block content %}
        {% endblock content %}
    </div>
  </div>

</main>

<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p>AllFoodRecipes is the place that can help you to get any references about <br>food recipes, you can search any food recipes by tags or search bar.  </p>
  </div>
</footer>
  <script src="{% static "js/jquery-3.4.1.min.js"%}" type="text/javascript"></script>
  <script src="{% static "js/bootstrap.bundle.min.js"%}" type="text/javascript"></script>
  <script src="{% static "js/script.js"%}" type="text/javascript"></script>
 <script src="{% static "js/lazy.js"%}" type="text/javascript"></script>
</body>
</html>