contact/urls.py
from django.contrib import admin
from django.urls import path

from .views import emailView, successView

app_name = 'contact'

urlpatterns = [
    path('', emailView, name='email'),
    path('success/', successView, name='success')
]

myfoodrecipes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from recipes.sitemap import Static_Sitemap
from recipes.sitemap import Recipe_Sitemap

sitemaps = {
    'recipes': Recipe_Sitemap(),
    'static': Static_Sitemap(),
}

urlpatterns = [
    path('', include('recipes.urls')),
    path('contact/', include('contact.urls')),
    path('adm/', admin.site.urls),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

contact/models.py
from django.db import models

# Create your models here.

contact/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(required=True)
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

contact/views.py
from django.core.mail import send_mail, BadHeaderError, EmailMessage
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import ContactForm

def emailView(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        
        if form.is_valid():
            name = form.cleaned_data['name']
            subject = form.cleaned_data['subject']
            to_email = form.cleaned_data['from_email']
            subject = name +' - ' + to_email + ' - ' + subject
            message = form.cleaned_data['message']
            try:
                email = EmailMessage(subject,message,'allfoodr@gmail.com',['support@allfoodrecipes.net'])
                email.send()
                messages.add_message(request, messages.INFO, '<strong>Thank you for getting in touch!</strong><br>We appreciate you contacting us. One of our colleagues will get back in touch with you soon!')
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            
            return redirect('/contact')
    return render(request, "contact/email.html", {'form': form, "title": "Contact Us"})

def successView(request):
    return HttpResponse('Success! Thank you for your message.')

contact/templates/contact/email.html
{% extends 'base.html' %}

{% block features %}
        <div class="container">
  <h1>Contact us</h1>
</div>
{% endblock features %}
{% block content %}


<div class="col-lg-8 blog-page">
{% if messages %}
<div class="alert alert-info" role="alert">
  {% for message in messages %}
  {{message|safe}}
  {% endfor %}
</div>
{% endif %}
<h5>If you have any questions don't hesitate to contact us</h5>
<div class="form-area">  
<br>

<form role="form" method="post">
    <div class="form-group">
        {% csrf_token %}
        <input type="text" class="form-control" id="name" name="name" placeholder="Name" maxlength="70" required>
    </div>
    <div class="form-group">
        <input type="email" class="form-control" required id="id_from_email" name="from_email" placeholder="Email" required>
    </div>

    <div class="form-group">
        <input type="text" class="form-control" id="subject" name="subject" required id="subject" placeholder="Subject" maxlength="70" required>
    </div>
    <div class="form-group">
    <textarea class="form-control" type="textarea" name="message" placeholder="Message" required id="id_message" maxlength="300" rows="7"></textarea>                
    </div>

    <button type="submit" id="submit" name="submit" class="btn btn-m btn-secondary">Submit Form</button>
</form>

</div>

{% endblock %}